### ISSUE TITLE
TypeScript + some ideas

### ISSUE THREAD

**Issue by allain** [Freak613/stage0#11]
Not an issue as much as a request for input.

While trying to understand the code, I rewrote index.js into a typescript file you'll find at the gist.

https://gist.github.com/allain/b662eebcd1a687f1fe030208fed89403

There are a couple comments which apply to the JavaScript version I'd be interested in your thoughts on.

Cheers

**Comment by Freak613** [comment]
Since I can't add comments to the code, I put them here:

1) I don't think it is a good idea to create Iterator each time, instead of reusing one. It increases GC pressure.
2) Where are you getting deprecation warning for createTreeWalker?
3) At the time, I was tested walker with different filters, in Chrome. And NodeFilter.SHOW_ALL always had best performance.
4) Reducing in collector should have noticeable performance hit.
5) I attached some functions to Walker or DOM nodes directly, since functions using `this` have better optimization in V8. Even such kind of monkey-patching.
6) I'd avoid additional checking at runtime such as `(!content)` or doing `node || content`. It will affect performance. V8 is getting better each day in optimizations, but from my experience these constructions will complicate compilers work.

**Comment by allain** [comment]
Thanks for the feedback:

1 & 2 Agreed, I'd switched it to that because createTreeWalker signature had been declared as deprecated (the one with the context as the last argument):
 https://github.com/Microsoft/TypeScript/blob/master/lib/lib.dom.d.ts#L4465

Also, the specs state that the version defined in DOM2 Traversal has been deprecated: https://developer.mozilla.org/en-US/docs/Web/API/Document/createTreeWalker#Specifications
3. Good to know
4. I'll have to run it to confirm, but you're probably right, I try to aim for clarity above performance most times, but in this case the benefit is arguably not there for my rewrite.
5. Neat. I'll try a compromise where the buildCollector reuses the refPath across instances but uses this internally to specify the node.
6. OK. Noted, I think view.collect() without argument should always be the case. Since the copying of the method from one clone to another will retain the refPaths using the closure it might be simpler at the cost of performance. I'll test and see for sure.

Thanks again.

**Comment by Freak613** [comment]
The last two arguments in createTreeWalker was just carry over and we can safely drop it, if any of them will be deprecated.

Making closure makes attaching it to the node not neccessary. As it doesn't use any data from the template, it could be returned in some custom object along with template node. Like `{collect, view}`.

**Comment by Freak613** [comment]
Extending DOM objects and access it's props has significant cost, because of deep inheritance tree, so it's better to avoid it when possible.

**Comment by Freak613** [comment]
Think we're done here.
