### ISSUE TITLE
What is a memoized dom ref exactly?

### ISSUE THREAD

**Issue by mrjjwright** [Freak613/stage0#13]
I have an extremely dumb set of related questions but I genuinely want to learn.   What is a memoized dom ref exactly?  I have seen it used on a couple different libs.   Is it one that is simply not looked up from the dom apis but the ref is cached?   Why is it so important and how does it differ from a normal simple var that points to an `HTMLElement`?  Is the purpose of using the h function to use  the TreeWalker api to super efficiently collect those refs and instantiate some dom tree, needed by some user of stage0 for some reason, in one single efficient step?   If you just have a single element to create with no children that need refs (here is the dumb question) I assume you don't need to use the `h` function?

**Comment by Freak613** [comment]
The paths are memoized, it's data needed to collect references in cloned nodes. Like `.firstChild.firstChild.nextSibling.firstChild`. Currently stage0 uses TreeWalker, so paths stored as number of `nextNode()` calls to get to the target node.
There is no mean to cache refs of original node, because refs are not translated during node cloning, so it needs to collect them for each clone.

Besides providing a way to collect references, I found that `h` could be helpful in just creating dom nodes when it's needed:
```javascript
App({
    icon:  h`<img class="my-icon">`
})
```

**Comment by mrjjwright** [comment]
I see now!  Thanks!
