### ISSUE TITLE
reuseNodes vs reconcile

### ISSUE THREAD

**Issue by mrjjwright** [Freak613/stage0#16]
Hi,  can somebody explain the differences between these 2 functions a bit more, I am not getting it.  What are some practical considerations in choosing between the 2.  If `reuseNodes` is a more performant version of `reconcile` than why not use it all the time?   Can you use it only if you can guarantee that a mode will not move visually in its order on the screen?

**Comment by ryansolid** [comment]
You should freshen up on Stephan Krause's (author of JS Framework Benchmark) article on the difference between Keyed and Non-Keyed. https://www.stefankrause.net/wp/?p=342 if you haven't recently.

In basic with mutable data you don't need explicit keys for it to be "keyed" as referential comparisons will serve the purpose. That's what ```reconcile``` uses, it's the basically same approach that libraries like Surplus and Solid use or any performant library that uses mutable data without explicit keys is going to use.

```reuseNodes``` is essentially the non keyed version of this. So instead of trying to find a reference to an object in array and move the position of element at that index around the algorithm assumes that items at the same index are the same and just attempts to apply any changes to it. This can save time it reduces reflows and style calculations that happen when moving elements. However internal state of the element like animations are lost.

**Comment by mrjjwright** [comment]
Ryan, amazing insightful answer as usual.  I can't thank you enough.
