### ISSUE TITLE
Reconcile question

### ISSUE THREAD

**Issue by mrjjwright** [Freak613/stage0#18]
I am having trouble getting this example to work: https://codesandbox.io/s/mo0vymp5m9?fontsize=14.  It's probably something stupid.  It's just an array of 3 strings.  On the first render, I render all 3 items.  Then I mutate the second element and render again.   It only renders 2 items on the second time.   Is that supposed to work?

Thanks!!

**Comment by Freak613** [comment]
It's some strange bug unfortunately.
Will look into it soon.

**Comment by mrjjwright** [comment]
ok, thanks!

**Comment by allain** [comment]
If it helps reuseNodes doesn't have this behaviour, it renders correctly:

https://codesandbox.io/s/pywx4x2x4j

**Comment by ryansolid** [comment]
I hit this issue when writing unit tests for my implementation (which is based on this one). I thought it was some logic I had changed adding disposing logic but it seems likely now it's from the source.

There is a condition I believe it was around full replace where it doesn't account for skipping over the common prefix and then does a shortcut optimization full replace with the remainder of the nodes rather than insert the nodes between the current indexed markers. The truth is the full replace is not always a full replace but occurs whenever a replace is required for single continuous section within the middle of the list.

For primitive value types like the example reuseNodes could make sense. But for any more structured data there are potential tradeoffs.

**Comment by Freak613** [comment]
Fixed in
https://github.com/Freak613/stage0/commit/0946b9e80ff6531c0e18c6151f12f5fe9c92f58e

Yes, it's inappropriately fell into full replace case.
Fixed in 0.0.21

PS: Don't forget to include beforeNode/afterNode in reconcile/keyed cases, if you try to render list among other siblings.

**Comment by mrjjwright** [comment]
Thank you!!
