### ISSUE TITLE
[FR] please add final min js's to the project or some public domain like CDN

### ISSUE THREAD

**Issue by trsh** [Freak613/stage0#4]
Please!

**Comment by ismail-codar** [comment]
A weak solution:
```js
<script src="https://unpkg.com/stage0@0.0.11/index.js"></script>
<script src="https://unpkg.com/stage0@0.0.11/reuseNodes.js"></script>
// ... other stage0 js files if required
```

**Comment by trsh** [comment]
@ismail-codar 

Not working. Needs to be converted to es5 orsmth.

```
Uncaught SyntaxError: Unexpected token export
Uncaught SyntaxError: Unexpected token export
Uncaught (in promise) TypeError: t is not a function
```

etc

**Comment by Freak613** [comment]
@trsh
`export` keyword only works in ES Modules
You can load script as module using
```
<script type="module" src="https://unpkg.com/stage0@0.0.11/index.js"></script>
```

**Comment by Freak613** [comment]
Simply you can try something like this:
```html
<script type="module" scr="https://unpkg.com/stage0@0.0.11/index.js"></script>
<script type="module">
import h from "https://unpkg.com/stage0@0.0.11/index.js"
const view = h`<div></div>`
console.debug({view})
</script>
```

**Comment by trsh** [comment]
export function h
export default h

this works with npm but really messes up things when I try to build a minified & uglified library that uses stage0. it should be one or another.

**Comment by Freak613** [comment]
No, it's correct exports expression, equal to
```javascript
exports {
    h: h,
    default: h
}
```
What you getting is possibly problem with how you importing stage0 into your library.

I've published minified versions, though I don't think it's correct or helps you a lot.
Because, if you developing library, people will definitely use bundlers for that. 
The library itself designed to be tree-shakable.
And if you testing your library in browser, it's better to compile code with bundler, that will handle all dependencies resolving.
Neither this way is not designed for production, where you definitely need to create minified/uglified bundles, instead of loading dependencies one-by-one.

You can load it using:
```html
<script src="https://unpkg.com/stage0@0.0.15/dist/index.min.js"></script>
```
The module will be under `window.stage0`.
You can load other files specifying their names from package.
You can check out yourself, if you update it from npm now, there will be `dist` folder with all published files.
